version: '3.8'

services:
  whatsapp-wizard:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: whatsapp-wizard-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY:-}
      - POSTHOG_HOST=${POSTHOG_HOST:-}
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    ports:
      - "3000:3000"
    volumes:
      - whatsapp_auth:/app/.wwebjs_auth
      - whatsapp_cache:/app/.wwebjs_cache
      - whatsapp_profile:/app/BTAA
      - whatsapp_dev:/app/DEV
      - media_files:/app/public/media
      - qr_codes:/app/public/qrcodes
      - app_logs:/app/logs
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { res.statusCode === 200 ? process.exit(0) : process.exit(1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  whatsapp_auth:
    driver: local
  whatsapp_cache:
    driver: local
  whatsapp_profile:
    driver: local
  whatsapp_dev:
    driver: local
  media_files:
    driver: local
  qr_codes:
    driver: local
  app_logs:
    driver: local

networks:
  whatsapp-network:
    driver: bridge
